.PHONY: help
help:
	echo "help: print this \ntest: run test for this project \nbuild: build idris library \nrun: run it if can"

.PHONY: test
test: 
	pack run test/test.ipkg


.PHONY: build
build: 
	pack build game-2048.ipkg


.PHONY: run
run: 
	pack run game-2048.ipkg
