[custom.all.screwdriver]
type   = "local"
path   = "."
ipkg   = "screwdriver/screwdriver.ipkg"

[custom.all.tentacle]
type   = "local"
path   = "."
ipkg   = "tentacle/tentacle.ipkg"

[custom.all.css-selector]
type   = "local"
path   = "."
ipkg   = "css-selector/css-selector.ipkg"

[custom.all.douban]
type   = "local"
path   = "."
ipkg   = "douban/douban.ipkg"

[custom.all.cheerio]
type   = "local"
path   = "."
ipkg   = "cheerio/cheerio.ipkg"


[custom.all.matrix]
type   = "local"
path   = "."
ipkg   = "matrix/matrix.ipkg"


[custom.all.game-2048]
type   = "local"
path   = "."
ipkg   = "game-2048.ipkg"